### ISSUE TITLE
When not querying for `edges` but passing filters for Relay nodes, calculated counts are incorrect

### ISSUE THREAD

**Issue by rsomani95** [MrThearMan/graphene-django-query-optimizer#79] opened 2024-03-11 21:20 UTC
### I have read the docs thoroughly before making this bug report.

- [X] Yes

### I have read through other open issues, and my issue is not a duplicate.

- [X] Yes

### What version of the library you are using?

0.2.11

### Which python version are you using?

3.12

### What operating system are you on?

Mac

### Description

This is more awkward behavior than a bug, but given how the optimizer runs filtering, you _need_ to query `edges` on a relay node to make filters run. This makes the output of queries like these incorrect:

```graphql
{
  pagedHousingCompanies(address:"fort") {
    totalCount
    # edges {
    #   node {
    #     streetAddress
    #   }
    # }
  }
}
```

However, if we uncomment the `edges { node ...` code above, the `totalCount` is correct.

In some custom filters, it's also possible to pass in incorrect values for the filter args since it never gets checked for value correctness, but only type correctness.

This is easy to work around give you know the quirk but feels like a sharp edge that'd be good to fix eventually.

**Comment by MrThearMan** [comment] 2024-03-11 22:06
This seems to be fixed in [0.3.0](https://github.com/MrThearMan/graphene-django-query-optimizer/releases/tag/v0.3.0)? Added a [regression test](https://github.com/MrThearMan/graphene-django-query-optimizer/blob/039eb537e9e25a31f8cbbace53e19adb0a2e1db0/tests/test_relay.py#L275-L299) just in case.

**Closed by MrThearMan** 2024-03-11 22:06 UTC
Labels: bug
